---
name: Run tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
  workflow_dispatch:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Lint
          run: just lint-test
